steps:
  - name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - '-r'
      - 'gs://hx_ontology-extender/extended_ontology/2022-12-09-18:19:58/family/'        
      - data/
    entrypoint: gsutil
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_LOCATION-docker.pkg.dev/$_ARTIFACT_REGISTRY_PROJECT_ID/$_REPOSITORY/$_IMAGE:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_LOCATION-docker.pkg.dev/$_ARTIFACT_REGISTRY_PROJECT_ID/$_REPOSITORY/$_IMAGE:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_LOCATION-docker.pkg.dev/$_ARTIFACT_REGISTRY_PROJECT_ID/$_REPOSITORY/$_IMAGE:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_LOCATION-docker.pkg.dev/$_ARTIFACT_REGISTRY_PROJECT_ID/$_REPOSITORY/$_IMAGE:$COMMIT_SHA'
timeout: 60m
options:
  substitutionOption: ALLOW_LOOSE
  machineType: 'E2_HIGHCPU_8'
substitutions:
  _GCR_HOSTNAME: us.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: knowledge-graph-server
  _DEPLOY_REGION: us-central1
  _LABELS: gcb-trigger-id=a458fd82-280a-4cdd-b80b-4594c16b12e4
  _TRIGGER_ID: a458fd82-280a-4cdd-b80b-4594c16b12e4
  _LOCATION: us
  _ARTIFACT_REGISTRY_PROJECT_ID: hx-package-repository
  _REPOSITORY: docker-images
  _IMAGE: knowledge-graph-server  
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - knowledge-graph-server
